export const routes = {
  home: "/",
  features: "/features",
  pricing: "/pricing",
  login: "/login",
  signup: "/signup",
  app: {
    root: "/app",
    leads: "/app/leads",
    lead: (id: string) => `/app/leads/${id}`,
    contacts: "/app/contacts",
    contact: (id: string) => `/app/contacts/${id}`,
    pipeline: "/app/pipeline",
    conversations: "/app/conversations",
    automations: "/app/automations",
    automation: (id: string) => `/app/automations/${id}`,
    ai: "/app/ai",
    analytics: "/app/analytics",
    integrations: "/app/integrations",
    team: "/app/team",
    settings: "/app/settings",
    billing: "/app/billing",
  },
} as const;
