import { useState, type ReactNode } from "react";
import { Link } from "react-router";
import { ArrowUpRight, Bot, CalendarClock, Check, Download, FileText, FlaskConical, HardDrive, Mail, Sparkles, Users, Workflow } from "lucide-react";
import { cn } from "@/lib/cn";
import { routes } from "@/lib/routes";
import { downloadCsv } from "@/lib/csv";
import { formatCurrency, formatDate, formatNumber } from "@/lib/format";
import { useUser } from "@/lib/auth/auth-context";
import { billingPlans, brandLabel, periodTotal, planById, planRank, seatPrice, usage, useBilling, type BillingCycle, type Invoice, type PlanId } from "@/lib/billing/data";
import { seatsUsed, useTeam } from "@/lib/team/data";
import { Alert, Badge, Button, ConfirmDialog, Progress, Tabs, useToast } from "@/components/ui";
import { PaymentModal, PlanModal, type PlanChange } from "@/components/billing/billing-modals";
import { CardMark } from "@/components/billing/card-mark";

const money = (n: number) => formatCurrency(Math.round(n * 100) / 100);
const shortDate = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" });

const statusBadge: Record<Invoice["status"], { label: string; variant: "success" | "neutral" | "danger" }> = {
  paid: { label: "Paid", variant: "success" },
  refunded: { label: "Refunded", variant: "neutral" },
  failed: { label: "Failed", variant: "danger" },
};

function downloadInvoice(invoice: Invoice, company: string, email: string) {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${invoice.number}</title>
<style>body{font:14px/1.5 system-ui,sans-serif;color:#0f172a;max-width:640px;margin:48px auto;padding:0 24px}h1{font-size:22px;margin:0}table{width:100%;border-collapse:collapse;margin:24px 0}td,th{padding:10px 0;border-bottom:1px solid #e2e8f0;text-align:left}td:last-child,th:last-child{text-align:right}.demo{background:#fef3c7;color:#92400e;padding:10px 14px;border-radius:8px;margin-bottom:24px}.muted{color:#64748b}</style></head><body>
<div class="demo"><strong>Demo invoice.</strong> Generated by the NEXORA AI frontend demo. No payment was taken.</div>
<h1>NEXORA AI · Invoice ${invoice.number}</h1>
<p class="muted">Issued ${formatDate(invoice.date)} · Billed to ${company} (${email})</p>
<table><thead><tr><th>Description</th><th>Period</th><th>Amount</th></tr></thead>
<tbody><tr><td>${invoice.description}</td><td>${formatDate(invoice.periodStart)} – ${formatDate(invoice.periodEnd)}</td><td>${money(invoice.amount)}</td></tr></tbody>
<tfoot><tr><th colspan="2">Total</th><th>${money(invoice.amount)}</th></tr></tfoot></table>
<p class="muted">Status: ${statusBadge[invoice.status].label}</p></body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
  Object.assign(document.createElement("a"), { href: url, download: `${invoice.number}.html` }).click();
  URL.revokeObjectURL(url);
}

function Panel({ title, description, action, children, className }: { title: string; description?: ReactNode; action?: ReactNode; children: ReactNode; className?: string }) {
  return (
    <section className={cn("rounded-lg border border-border bg-white shadow-xs", className)}>
      <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border px-4 py-3.5 sm:px-5">
        <div className="min-w-0">
          <h2 className="text-sm font-semibold text-ink">{title}</h2>
          {description && <p className="mt-0.5 text-xs text-muted">{description}</p>}
        </div>
        {action}
      </div>
      {children}
    </section>
  );
}

function Meter({ icon, label, used, limit, format = formatNumber, note }: { icon: ReactNode; label: string; used: number; limit: number; format?: (n: number) => string; note?: string }) {
  const unlimited = !Number.isFinite(limit);
  const pct = unlimited ? 0 : Math.round((used / limit) * 100);
  return (
    <div className="rounded-md border border-border p-3.5">
      <div className="flex items-center gap-2">
        <span className="flex size-6 items-center justify-center rounded-sm bg-sunken text-muted [&_svg]:size-3.5">{icon}</span>
        <p className="min-w-0 flex-1 truncate text-sm font-medium text-ink">{label}</p>
        <span className={cn("text-metric text-xs font-medium", pct >= 90 ? "text-danger" : pct >= 75 ? "text-warning-text" : "text-muted")}>{unlimited ? "Unlimited" : `${pct}%`}</span>
      </div>
      <Progress value={unlimited ? 0 : used} max={unlimited ? 1 : limit} tone="auto" className="mt-3" />
      <p className="mt-2 text-xs text-muted">
        <span className="text-metric font-medium text-ink">{format(used)}</span>
        {unlimited ? " used" : ` of ${format(limit)}`}
        {note && <span className="text-subtle"> · {note}</span>}
      </p>
    </div>
  );
}

export default function BillingPage() {
  const user = useUser();
  const { toast } = useToast();
  const [state, setState] = useBilling(user.id, user.email);
  const [team] = useTeam(user);
  const [cycleView, setCycleView] = useState<BillingCycle>(state.cycle);
  const [planDraft, setPlanDraft] = useState<{ plan: PlanId; cycle: BillingCycle } | null>(null);
  const [paying, setPaying] = useState(false);
  const [cancelling, setCancelling] = useState(false);
  const [showAll, setShowAll] = useState(false);

  const plan = planById[state.plan];
  const used = seatsUsed(team.members);
  const perSeat = seatPrice(state.plan, state.cycle);
  const total = periodTotal(state.plan, state.cycle, state.seats);
  const annualSaving = periodTotal(state.plan, "monthly", state.seats) * 12 - periodTotal(state.plan, "annual", state.seats);
  const invoices = [...state.invoices].sort((a, b) => b.date - a.date);
  const shownInvoices = showAll ? invoices : invoices.slice(0, 6);
  const pm = state.paymentMethod;
  const today = new Date();
  const usageStart = new Date(today.getFullYear(), today.getMonth(), 1);
  const usageEnd = new Date(today.getFullYear(), today.getMonth() + 1, 1);

  async function applyChange(change: PlanChange) {
    await new Promise((r) => setTimeout(r, 1100));
    const now = Date.now();
    setState((s) => {
      const cycleChanged = change.cycle !== s.cycle;
      const end = new Date(now);
      end.setMonth(end.getMonth() + (change.cycle === "annual" ? 12 : 1));
      const invoice: Invoice | null =
        change.dueToday > 0
          ? {
              id: `inv_${now.toString(36)}`,
              number: `NX-${new Date(now).getFullYear()}-${String(1043 + s.invoices.length).padStart(4, "0")}`,
              date: now,
              periodStart: now,
              periodEnd: cycleChanged ? end.getTime() : s.periodEnd,
              description: `${planById[change.plan].name} · ${change.seats} seats · ${change.cycle === "annual" ? "Annual" : "Monthly"}${cycleChanged ? "" : " (prorated)"}`,
              seats: change.seats,
              amount: change.dueToday,
              status: "paid",
            }
          : null;
      return {
        ...s,
        plan: change.plan,
        cycle: change.cycle,
        seats: change.seats,
        cancelAtPeriodEnd: false,
        periodStart: cycleChanged ? now : s.periodStart,
        periodEnd: cycleChanged ? end.getTime() : s.periodEnd,
        invoices: invoice ? [invoice, ...s.invoices] : s.invoices,
      };
    });
    setCycleView(change.cycle);
    setPlanDraft(null);
    toast({
      variant: "success",
      title: change.plan !== state.plan ? `You're on ${planById[change.plan].name}` : "Subscription updated",
      description: change.dueToday > 0 ? `Demo charge of ${money(change.dueToday)} added to your invoices.` : change.dueToday < 0 ? `${money(-change.dueToday)} credit applied to your next invoice.` : "Changes take effect immediately.",
    });
  }

  function choosePlan(id: PlanId) {
    if (id === "enterprise") {
      toast({ variant: "success", title: "Request sent to sales", description: "Demo: a solutions engineer would reach out within one business day." });
      return;
    }
    setPlanDraft({ plan: id, cycle: cycleView });
  }

  return (
    <>
      <title>Billing · NEXORA AI</title>

      <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h1 className="font-display text-2xl font-semibold tracking-tight text-ink sm:text-3xl">Billing</h1>
            <Badge variant="warning" size="sm">
              <FlaskConical className="size-3" aria-hidden />
              Demo
            </Badge>
          </div>
          <p className="mt-1 text-base text-muted">Plan, usage and invoices for {user.company}.</p>
        </div>
        <Button variant="secondary" leftIcon={<Sparkles />} onClick={() => setPlanDraft({ plan: state.plan, cycle: state.cycle })} className="w-full sm:w-auto">
          Change plan
        </Button>
      </header>

      <Alert
        tone="info"
        className="mt-5"
        title="This is a frontend demo"
        description="All billing data is simulated and stored only in your browser. No payments are processed, no cards are charged and invoices aren't real."
      />

      {state.cancelAtPeriodEnd && (
        <Alert
          tone="warning"
          className="mt-3"
          title={`Your ${plan.name} plan ends on ${formatDate(state.periodEnd)}`}
          description={
            <span className="flex flex-wrap items-center gap-x-3 gap-y-1">
              You'll keep access until then.
              <button
                type="button"
                onClick={() => {
                  setState((s) => ({ ...s, cancelAtPeriodEnd: false }));
                  toast({ variant: "success", title: "Subscription resumed", description: `${plan.name} renews on ${formatDate(state.periodEnd)}.` });
                }}
                className="font-medium underline"
              >
                Resume subscription
              </button>
            </span>
          }
        />
      )}

      <div className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-3 [&>*]:min-w-0">
        <Panel
          title="Current plan"
          className="lg:col-span-2"
          action={
            <Badge variant={state.cancelAtPeriodEnd ? "warning" : "success"} dot size="sm">
              {state.cancelAtPeriodEnd ? "Cancelling" : "Active"}
            </Badge>
          }
        >
          <div className="grid gap-5 p-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:p-5">
            <div className="min-w-0">
              <p className="flex flex-wrap items-center gap-2">
                <span className="font-display text-2xl font-semibold text-ink">{plan.name}</span>
                <Badge variant="primary" appearance="outline" size="sm">
                  {state.cycle === "annual" ? "Annual" : "Monthly"}
                </Badge>
              </p>
              <p className="mt-1 text-sm text-muted">{plan.description}</p>
              <p className="mt-4 flex flex-wrap items-baseline gap-x-2">
                <span className="text-metric text-3xl font-semibold text-ink">{money(total)}</span>
                <span className="text-sm text-muted">
                  per {state.cycle === "annual" ? "year" : "month"} · {state.seats} seats × ${perSeat}
                </span>
              </p>
            </div>
            <dl className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm sm:grid-cols-1 sm:text-right">
              <div>
                <dt className="text-xs text-muted">Billing cycle</dt>
                <dd className="font-medium text-ink">{state.cycle === "annual" ? `${formatDate(state.periodStart)} – ${formatDate(state.periodEnd)}` : `${shortDate.format(state.periodStart)} – ${shortDate.format(state.periodEnd)}`}</dd>
              </div>
              <div>
                <dt className="text-xs text-muted">{state.cancelAtPeriodEnd ? "Plan ends" : "Next invoice"}</dt>
                <dd className="font-medium text-ink">
                  {formatDate(state.periodEnd)}
                  {!state.cancelAtPeriodEnd && <span className="block text-xs font-normal text-muted">{money(total)}</span>}
                </dd>
              </div>
            </dl>
          </div>
          <div className="flex flex-col gap-2 border-t border-border bg-canvas px-4 py-3 sm:flex-row sm:items-center sm:px-5">
            {state.cycle === "monthly" && annualSaving > 0 && (
              <Button size="sm" onClick={() => setPlanDraft({ plan: state.plan, cycle: "annual" })} leftIcon={<CalendarClock />}>
                <span className="min-[400px]:hidden">Go annual · save {money(annualSaving)}</span>
                <span className="max-[399px]:hidden">Switch to annual · save {money(annualSaving)}/yr</span>
              </Button>
            )}
            <Button size="sm" variant="secondary" onClick={() => setPlanDraft({ plan: state.plan, cycle: state.cycle })} leftIcon={<Users />}>
              Change seats
            </Button>
            {!state.cancelAtPeriodEnd && (
              <button type="button" onClick={() => setCancelling(true)} className="text-xs font-medium text-muted hover:text-danger sm:ml-auto">
                Cancel subscription
              </button>
            )}
          </div>
        </Panel>

        <Panel title="Payment method" action={<Button size="xs" variant="secondary" onClick={() => setPaying(true)}>Update</Button>}>
          <div className="p-4 sm:p-5">
            <div className="relative overflow-hidden rounded-lg bg-gradient-to-br from-ink via-ink to-primary-active p-4 text-white shadow-md">
              <div className="flex items-center justify-between">
                <span className="rounded-sm bg-white px-1.5 py-1">
                  <CardMark brand={pm.brand} className="h-3.5" />
                </span>
                <span className="text-2xs font-medium uppercase tracking-wider text-white/60">Demo card</span>
              </div>
              <p className="text-metric mt-6 text-lg tracking-[0.2em]">•••• •••• •••• {pm.last4}</p>
              <div className="mt-3 flex items-end justify-between text-xs">
                <span className="truncate text-white/80">{pm.name || user.name}</span>
                <span className="text-white/80">
                  {String(pm.expMonth).padStart(2, "0")}/{String(pm.expYear).slice(-2)}
                </span>
              </div>
            </div>
            <dl className="mt-4 space-y-2 text-sm">
              <div className="flex items-center justify-between gap-3">
                <dt className="text-muted">Card</dt>
                <dd className="text-ink">
                  {brandLabel[pm.brand]} ending {pm.last4}
                </dd>
              </div>
              <div className="flex items-center justify-between gap-3">
                <dt className="shrink-0 text-muted">Billing email</dt>
                <dd className="flex min-w-0 items-center gap-1.5 text-ink">
                  <Mail className="size-3.5 shrink-0 text-subtle" aria-hidden />
                  <span className="truncate">{state.billingEmail}</span>
                </dd>
              </div>
            </dl>
          </div>
        </Panel>
      </div>

      <Panel
        title="Usage this month"
        description={`${shortDate.format(usageStart)} – ${shortDate.format(usageEnd)} · AI credits reset ${shortDate.format(usageEnd)}`}
        className="mt-4"
        action={
          <Link to={routes.app.team} className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline">
            Manage team
            <ArrowUpRight className="size-3" aria-hidden />
          </Link>
        }
      >
        <div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-5 xl:grid-cols-5">
          <Meter icon={<Users />} label="Seats" used={used} limit={state.seats} note={`${plan.limits.users === Infinity ? "no" : plan.limits.users} max`} />
          <Meter icon={<Bot />} label="AI credits" used={usage.aiCredits} limit={plan.limits.aiCredits} />
          <Meter icon={<Users />} label="Contacts" used={usage.contacts} limit={plan.limits.contacts} />
          <Meter icon={<Workflow />} label="Automation runs" used={usage.runs} limit={plan.limits.runs} />
          <Meter icon={<HardDrive />} label="Storage" used={usage.storageGb} limit={plan.limits.storageGb} format={(n) => `${n} GB`} />
        </div>
      </Panel>

      <section aria-labelledby="plans-heading" className="mt-8">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 id="plans-heading" className="type-h3">
              Plans
            </h2>
            <p className="mt-1 text-sm text-muted">Prices per seat, per month. Change or cancel anytime.</p>
          </div>
          <div className="flex items-center gap-2">
            <Tabs
              variant="segmented"
              value={cycleView}
              onValueChange={(v) => setCycleView(v as BillingCycle)}
              items={[
                { value: "monthly", label: "Monthly" },
                { value: "annual", label: "Annual" },
              ]}
            />
            <span className="text-xs font-medium text-success-text">Save up to 17%</span>
          </div>
        </div>

        <div className="scrollbar-none -mx-4 mt-4 flex snap-x snap-mandatory scroll-px-4 gap-3 overflow-x-auto px-4 pb-1 sm:mx-0 sm:grid sm:grid-cols-2 sm:overflow-visible sm:px-0 xl:grid-cols-4">
          {billingPlans.map((p) => {
            const current = p.id === state.plan;
            const price = cycleView === "annual" ? p.annual : p.monthly;
            const cta = current ? "Current plan" : p.id === "enterprise" ? "Contact sales" : planRank[p.id] > planRank[state.plan] ? `Upgrade to ${p.name}` : `Downgrade to ${p.name}`;
            return (
              <article
                key={p.id}
                className={cn(
                  "flex w-[80%] max-w-xs shrink-0 snap-start flex-col rounded-lg border bg-white p-5 shadow-xs sm:w-auto sm:max-w-none",
                  current ? "border-primary ring-1 ring-primary" : "border-border",
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <h3 className="text-base font-semibold text-ink">{p.name}</h3>
                  {current ? (
                    <Badge variant="primary" appearance="solid" size="sm">
                      Current
                    </Badge>
                  ) : (
                    p.popular && (
                      <Badge variant="primary" size="sm">
                        Popular
                      </Badge>
                    )
                  )}
                </div>
                <p className="mt-1 text-sm text-muted">{p.description}</p>
                <p className="mt-4 flex items-baseline gap-1">
                  {price === null ? (
                    <span className="font-display text-2xl font-semibold text-ink">Custom</span>
                  ) : (
                    <>
                      <span className="text-metric text-3xl font-semibold text-ink">${price}</span>
                      <span className="text-xs text-muted">/ seat / mo</span>
                    </>
                  )}
                </p>
                <p className="mt-0.5 h-4 text-xs text-subtle">{price !== null && cycleView === "annual" ? "Billed annually" : price === null ? "Volume pricing" : "Billed monthly"}</p>
                <Button
                  size="sm"
                  variant={current ? "secondary" : planRank[p.id] > planRank[state.plan] ? "primary" : "secondary"}
                  disabled={current && cycleView === state.cycle}
                  onClick={() => (current ? setPlanDraft({ plan: p.id, cycle: cycleView }) : choosePlan(p.id))}
                  className="mt-4 w-full"
                >
                  {current && cycleView !== state.cycle ? `Switch to ${cycleView}` : cta}
                </Button>
                <ul className="mt-4 space-y-2 border-t border-border pt-4">
                  {p.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm text-ink">
                      <Check className="mt-0.5 size-3.5 shrink-0 text-primary" aria-hidden />
                      {f}
                    </li>
                  ))}
                </ul>
              </article>
            );
          })}
        </div>
      </section>

      <Panel
        title="Invoice history"
        description={`${invoices.length} invoices · sent to ${state.billingEmail}`}
        className="mt-8"
        action={
          <Button
            size="xs"
            variant="secondary"
            leftIcon={<Download />}
            onClick={() => downloadCsv("nexora-invoices.csv", [["Invoice", "Date", "Description", "Amount", "Status"], ...invoices.map((i) => [i.number, formatDate(i.date), i.description, i.amount.toFixed(2), statusBadge[i.status].label])])}
          >
            Export CSV
          </Button>
        }
      >
        <table className="hidden w-full text-left text-sm md:table">
          <thead className="border-b border-border bg-canvas text-xs text-muted">
            <tr>
              <th scope="col" className="px-5 py-2.5 font-medium">
                Invoice
              </th>
              <th scope="col" className="px-4 py-2.5 font-medium">
                Date
              </th>
              <th scope="col" className="hidden px-4 py-2.5 font-medium lg:table-cell">
                Description
              </th>
              <th scope="col" className="px-4 py-2.5 text-right font-medium">
                Amount
              </th>
              <th scope="col" className="px-4 py-2.5 font-medium">
                Status
              </th>
              <th scope="col" className="w-14 px-4 py-2.5">
                <span className="sr-only">Download</span>
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {shownInvoices.map((inv) => (
              <tr key={inv.id} className="hover:bg-canvas/60">
                <td className="px-5 py-3">
                  <span className="flex items-center gap-2 font-medium text-ink">
                    <FileText className="size-4 text-subtle" aria-hidden />
                    {inv.number}
                  </span>
                  <span className="mt-0.5 block text-xs text-muted lg:hidden">{inv.description}</span>
                </td>
                <td className="whitespace-nowrap px-4 py-3 text-muted">{formatDate(inv.date)}</td>
                <td className="hidden px-4 py-3 text-muted lg:table-cell">{inv.description}</td>
                <td className="text-metric px-4 py-3 text-right font-medium text-ink">{money(inv.amount)}</td>
                <td className="px-4 py-3">
                  <Badge variant={statusBadge[inv.status].variant} size="sm">
                    {statusBadge[inv.status].label}
                  </Badge>
                </td>
                <td className="px-4 py-3 text-right">
                  <Button variant="ghost" size="icon-sm" onClick={() => downloadInvoice(inv, user.company, state.billingEmail)} aria-label={`Download invoice ${inv.number}`}>
                    <Download />
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <ul className="divide-y divide-border md:hidden">
          {shownInvoices.map((inv) => (
            <li key={inv.id} className="flex items-center gap-3 px-4 py-3">
              <div className="min-w-0 flex-1">
                <p className="flex items-center gap-2 text-sm font-medium text-ink">
                  {inv.number}
                  <Badge variant={statusBadge[inv.status].variant} size="sm">
                    {statusBadge[inv.status].label}
                  </Badge>
                </p>
                <p className="mt-0.5 truncate text-xs text-muted">
                  {formatDate(inv.date)} · {inv.description}
                </p>
              </div>
              <span className="text-metric shrink-0 text-sm font-medium text-ink">{money(inv.amount)}</span>
              <Button variant="ghost" size="icon-sm" onClick={() => downloadInvoice(inv, user.company, state.billingEmail)} aria-label={`Download invoice ${inv.number}`} className="-mr-1.5 shrink-0">
                <Download />
              </Button>
            </li>
          ))}
        </ul>

        {invoices.length > 6 && (
          <div className="border-t border-border px-4 py-2.5 text-center">
            <button type="button" onClick={() => setShowAll((v) => !v)} className="text-xs font-medium text-primary hover:underline">
              {showAll ? "Show fewer" : `Show all ${invoices.length} invoices`}
            </button>
          </div>
        )}
      </Panel>

      <PlanModal open={Boolean(planDraft)} state={state} initial={planDraft} seatsUsed={used} onClose={() => setPlanDraft(null)} onConfirm={applyChange} />
      <PaymentModal
        open={paying}
        current={pm}
        onClose={() => setPaying(false)}
        onSave={async (method) => {
          await new Promise((r) => setTimeout(r, 900));
          setState((s) => ({ ...s, paymentMethod: method }));
          setPaying(false);
          toast({ variant: "success", title: "Payment method updated", description: `${brandLabel[method.brand]} ending ${method.last4} is now your default. (Demo)` });
        }}
      />
      <ConfirmDialog
        open={cancelling}
        onClose={() => setCancelling(false)}
        onConfirm={() => {
          setState((s) => ({ ...s, cancelAtPeriodEnd: true }));
          setCancelling(false);
          toast({ variant: "info", title: "Subscription cancelled", description: `You'll keep ${plan.name} until ${formatDate(state.periodEnd)}.` });
        }}
        tone="danger"
        title={`Cancel ${plan.name}?`}
        description={`Your team keeps access until ${formatDate(state.periodEnd)}. After that, the workspace becomes read-only. You can resume anytime before then.`}
        confirmLabel="Cancel subscription"
        cancelLabel="Keep plan"
      />
    </>
  );
}
